### ISSUE TITLE
Move over to JuliaSparse

### ISSUE THREAD

**Issue by lindahua** [JuliaSparse/SparseVectors.jl#1]
The package provides many of the useful functions and has been well tested. I think it is ready for JuliaSparse.

@tkelman Please let me know if you think it is good to go.

**Comment by tkelman** [comment]
I haven't kicked the tires myself yet, but the code looks really good so far, so I'd say may as well. @ViralBShah thoughts?

**Comment by ViralBShah** [comment]
I saw the README, and I really like it. @lindahua I think you already are an owner of JuliaSparse.

**Comment by lindahua** [comment]
Done!
